/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define LOTTIE_CACHE_SUPPORT 1

#define LOTTIE_THREAD_SUPPORT 1

#ifdef _WIN32
#include <stdlib.h>
#define realpath(x, y) _fullpath((y), (x), _MAX_PATH)
#endif
